apiVersion: v1
kind: Service
metadata:
  name: arthub-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP 
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: arthub-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthub-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arthub-app
  template:
    metadata:
      labels:
        app: arthub-app
    spec:
      containers:
        - name: arthub-app
          image: arthub-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/bd_spring_jpa?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arthub-secrets
                  key: mysql-root-password
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arthub-secrets
                  key: stripe-api-key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: arthub-secrets
                  key: stripe-public-key